CREATE DATABASE IF NOT EXISTS prograwebproyecto;

USE prograwebproyecto;

CREATE TABLE IF NOT EXISTS GENRE (
	genre_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    deletedAt DATETIME,
    CONSTRAINT PK_genre_Id PRIMARY KEY (genre_Id)
);

CREATE TABLE IF NOT EXISTS ARTIST (
	artist_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    deletedAt DATETIME,
    CONSTRAINT PK_artist_Id PRIMARY KEY (artist_Id)
);

CREATE TABLE IF NOT EXISTS SONG (
	song_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    deletedAt DATETIME,
    CONSTRAINT PK_song_Id PRIMARY KEY (song_Id)
);

CREATE TABLE IF NOT EXISTS USER (
	user_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
    email VARCHAR(255) NOT NULL,
	createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    deletedAt DATETIME,
    CONSTRAINT PK_user_Id PRIMARY KEY (user_Id)
);

CREATE TABLE IF NOT EXISTS QUIZ (
	quiz_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    user_Id INT NOT NULL,
    question_1 INT NOT NULL,
    question_2 INT NOT NULL,
    question_3 INT NOT NULL,
    CONSTRAINT PK_quiz_Id PRIMARY KEY (quiz_Id),
    CONSTRAINT FK_quiz_user_Id FOREIGN KEY (user_Id) REFERENCES USER(user_Id),
    CONSTRAINT FK_question_1 FOREIGN KEY (question_1) REFERENCES GENRE(genre_Id),
    CONSTRAINT FK_question_2 FOREIGN KEY (question_2) REFERENCES ARTIST(artist_Id),
    CONSTRAINT FK_question_3 FOREIGN KEY (question_3) REFERENCES SONG(song_Id)
);

CREATE TABLE IF NOT EXISTS COUNTRY (
	country_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    code VARCHAR(3) NOT NULL,
    CONSTRAINT PK_country_Id PRIMARY KEY (country_Id)
);

CREATE TABLE IF NOT EXISTS PERSON (
	person_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    user_Id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    birthdate DATE NOT NULL,
    sex VARCHAR(10) NOT NULL,
    country_Id INT NOT NULL,
	createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    deletedAt DATETIME,
    CONSTRAINT PK_person_Id PRIMARY KEY (person_Id),
    CONSTRAINT FK_person_user_Id FOREIGN KEY (user_Id) REFERENCES USER(user_Id),
    CONSTRAINT FK_country_Id FOREIGN KEY (country_Id) REFERENCES COUNTRY(country_Id)
);

CREATE TABLE IF NOT EXISTS EMOTION_TYPE (
	emotiontype_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    name VARCHAR(10) NOT NULL,
    CONSTRAINT PK_emotiontype_Id PRIMARY KEY (emotiontype_Id)
);

CREATE TABLE IF NOT EXISTS EMOTION (
	emotion_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    name VARCHAR(10) NOT NULL,
    emotiontype_Id INT NOT NULL,
    CONSTRAINT PK_emotion_Id PRIMARY KEY (emotion_Id),
    CONSTRAINT FK_emotiontype_Id FOREIGN KEY (emotiontype_Id) REFERENCES EMOTION_TYPE(emotiontype_Id)
);

CREATE TABLE IF NOT EXISTS EMOTION_ANALYSIS (
	emotionanalysis_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    emotion_Id INT NOT NULL,
    confidence DOUBLE(6,5) NOT NULL,
    date DATETIME NOT NULL,
    CONSTRAINT PK_emotionanalysis_Id PRIMARY KEY (emotionanalysis_Id),
    CONSTRAINT FK_emotion_Id FOREIGN KEY (emotion_Id) REFERENCES EMOTION(emotion_Id)
);

CREATE TABLE IF NOT EXISTS HISTORY (
	history_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    user_Id INT NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    deletedAt DATETIME,
    CONSTRAINT PK_history_Id PRIMARY KEY (history_Id),
    CONSTRAINT FK_user_Id FOREIGN KEY (user_Id) REFERENCES USER(user_Id)
);

CREATE TABLE IF NOT EXISTS TYPE (
	type_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT PK_type_Id PRIMARY KEY (type_Id)
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION (
	recommendation_Id INT AUTO_INCREMENT NOT NULL UNIQUE,
    history_Id INT NOT NULL,
    spotify_id INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    URL TEXT NOT NULL,
    feedback BIT NOT NULL,
    `JSON` JSON NOT NULL,
    type_Id INT NOT NULL,
    emotion_1 INT NOT NULL,
    emotion_2 INT NOT NULL,
    emotion_3 INT NOT NULL,
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL,
    deletedAt DATETIME,
    CONSTRAINT PK_recommendation_Id PRIMARY KEY (recommendation_Id),
    CONSTRAINT FK_history_Id FOREIGN KEY (history_Id) REFERENCES HISTORY(history_Id),
    CONSTRAINT FK_type_Id FOREIGN KEY (type_Id) REFERENCES TYPE(type_Id),
    CONSTRAINT FK_emotion_1 FOREIGN KEY (emotion_1) REFERENCES EMOTION(emotion_Id),
    CONSTRAINT FK_emotion_2 FOREIGN KEY (emotion_2) REFERENCES EMOTION(emotion_Id),
    CONSTRAINT FK_emotion_3 FOREIGN KEY (emotion_3) REFERENCES EMOTION(emotion_Id)
);

INSERT INTO COUNTRY (name, code)
VALUES ("Afganistán","AFG"),
("Åland Islands","ALI"),
("Albania","ALB"),
("Alemania","DEU"),
("Andorra","AND"),
("Angola","AGO"),
("Anguila","AIA"),
("Antártida","ATA"),
("Antigua y Barbuda","ATG"),
("Antillas Neerlandesas","ANT"),
("Arabia Saudita","SAU"),
("Argelia","DZA"),
("Argentina","ARG"),
("Armenia","ARM"),
("Aruba","ABW"),
("Australia","AUS"),
("Austria","AUT"),
("Azerbaiyán","AZE"),
("Bahamas","BHS"),
("Bahrein","BHR"),
("Bangladesh","BGD"),
("Barbados","BRB"),
("Belarús","BLR"),
("Bélgica","BEL"),
("Bélgica-Luxemburgo","BLX"),
("Belice","BLZ"),
("Benin","BEN"),
("Bermudas","BMU"),
("Bhután","BTN"),
("Bolivia","BOL"),
("Bonaire","BES"),
("Bosnia y Herzegovina","BIH"),
("Botswana","BWA"),
("Brasil","BRA"),
("Brunei Darussalam","BRN"),
("Bulgaria","BGR"),
("Burkina Faso","BFA"),
("Burundi","BDI"),
("Cabo Verde","CPV"),
("Camboya","KHM"),
("Camerún","CMR"),
("Canadá","CAN"),
("Categorías especiales","SPE"),
("Chad","TCD"),
("Checoslovaquia","CSK"),
("Chile","CHL"),
("China","CHN"),
("Chipre","CYP"),
("Colombia","COL"),
("Comando I del Pacífico de Estados Unidos","USP"),
("Comoras","COM"),
("Rep. del Congo","COG"),
("Rep. Dem. del Congo","ZAR"),
("Rep. de Corea","KOR"),
("Rep. Dem. de Corea","PRK"),
("Costa Rica","CRI"),
("Côte d'Ivoire","CIV"),
("Croacia","HRV"),
("Cuba","CUB"),
("Curacao","CUW"),
("Dinamarca","DNK"),
("Djibouti","DJI"),
("Dominica","DMA"),
("Ecuador","ECU"),
("Rep. Árabe de Egipto","EGY"),
("El Salvador","SLV"),
("Emiratos Árabes Unidos","ARE"),
("Eritrea","ERI"),
("Eslovenia","SVN"),
("España","ESP"),
("Estados Unidos","USA"),
("Estonia","EST"),
("Etiopía (excluida Eritrea)","ETH"),
("Etiopía (incluida Eritrea)","ETF"),
("European Union","EUN"),
("Ex Sudán","SDN"),
("Federación de Rusia","RUS"),
("Fiji","FJI"),
("Filipinas","PHL"),
("Finlandia","FIN"),
("Fm Panama Cz","PCZ"),
("Fm Rhod Nyas","ZW1"),
("Fm Tanganyik","TAN"),
("Fm Vietnam DR","VDR"),
("Fm Vietnam Rp","SVR"),
("Fm Zanz-Pemb","ZPM"),
("Francia","FRA"),
("Gabón","GAB"),
("Gambia","GMB"),
("Gaza Strip","GAZ"),
("Georgia","GEO"),
("Ghana","GHA"),
("Gibraltar","GIB"),
("Granada","GRD"),
("Grecia","GRC"),
("Groenlandia","GRL"),
("Guadalupe","GLP"),
("Guam","GUM"),
("Guatemala","GTM"),
("Guayana Francesa","GUF"),
("Guinea","GIN"),
("Guinea Ecuatorial","GNQ"),
("Guinea-Bissau","GNB"),
("Guyana","GUY"),
("Haití","HTI"),
("Honduras","HND"),
("Hong Kong (China)","HKG"),
("Hungría","HUN"),
("India","IND"),
("Indonesia","IDN"),
("Rep. Islámica del Irán","IRN"),
("Iraq","IRQ"),
("Irlanda","IRL"),
("Isla Bouvet","BVT"),
("Isla Bunker","BUN"),
("Isla de Navidad","CXR"),
("Isla Norfolk","NFK"),
("Islandia","ISL"),
("Islas Caimán","CYM"),
("Islas Cocos (Keeling)","CCK"),
("Islas Cook","COK"),
("Islas del Pacífico","PCE"),
("Islas Falkland","FLK"),
("Islas Feroe","FRO"),
("Islas Georgias del Sur y Sandwich del Sur","SGS"),
("Islas Heard y McDonald","HMD"),
("Islas Marshall","MHL"),
("Islas Salomón","SLB"),
("Islas Turcas y Caicos","TCA"),
("Islas Ultramarinas Menores de Estados Unidos","UMI"),
("Islas Vírgenes (EE.UU.)","VIR"),
("Islas Vírgenes Británicas","VGB"),
("Islas Wallis y Futuna","WLF"),
("Israel","ISR"),
("Italia","ITA"),
("Jamaica","JAM"),
("Japón","JPN"),
("Jhonston Island","JTN"),
("Jordania","JOR"),
("Kazajstán","KAZ"),
("Kenya","KEN"),
("Kirguistán","KGZ"),
("Kiribati","KIR"),
("Kosovo","KSV"),
("Kuwait","KWT"),
("Lesotho","LSO"),
("Letonia","LVA"),
("Líbano","LBN"),
("Liberia","LBR"),
("Libia","LBY"),
("Liechtenstein","LIE"),
("Lituania","LTU"),
("Luxemburgo","LUX"),
("Macao","MAC"),
("Macedonia, ex Rep. Yugoslava de","MKD"),
("Madagascar","MDG"),
("Malasia","MYS"),
("Malawi","MWI"),
("Maldivas","MDV"),
("Malí","MLI"),
("Malta","MLT"),
("Mariana","MNP"),
("Marruecos","MAR"),
("Martinica","MTQ"),
("Mauricio","MUS"),
("Mauritania","MRT"),
("Mayotte","MYT"),
("México","MEX"),
("Estados Fed. de Micronesia","FSM"),
("Midway Islands","MID"),
("Mónaco","MCO"),
("Mongolia","MNG"),
("Montenegro","MNT"),
("Montserrat","MSR"),
("Mozambique","MOZ"),
("Mundo","WLD"),
("Myanmar","MMR"),
("Namibia","NAM"),
("Nauru","NRU"),
("Nepal","NPL"),
("Nicaragua","NIC"),
("Níger","NER"),
("Nigeria","NGA"),
("Niue","NIU"),
("No especificados","UNS"),
("Noruega","NOR"),
("Nueva Caledonia","NCL"),
("Nueva Zelandia","NZL"),
("Omán","OMN"),
("Otra zona de Asia, no esp.","OAS"),
("Países Bajos","NLD"),
("Pakistán","PAK"),
("Palau","PLW"),
("Panamá","PAN"),
("Papua Nueva Guinea","PNG"),
("Paraguay","PRY"),
("Pen Malaysia","PMY"),
("Perú","PER"),
("Pitcairn","PCN"),
("Polinesia Francesa","PYF"),
("Polonia","POL"),
("Portugal","PRT"),
("Puerto Rico","PRI"),
("Qatar","QAT"),
("Reino Unido","GBR"),
("República Árabe Siria","SYR"),
("República Centroafricana","CAF"),
("República Checa","CZE"),
("República de Moldova","MDA"),
("República Democrática Alemana","DDR"),
("República Democrática Popular Lao","LAO"),
("República Dominicana","DOM"),
("República Eslovaca","SVK"),
("Reunión","REU"),
("Rumania","ROM"),
("Rwanda","RWA"),
("Ryukyu Is","RYU"),
("Sabah","SBH"),
("Sahara Occidental","ESH"),
("Saint Kitts y Nevis","KNA"),
("Saint Kitts-Nevis-Anguilla-Aru","KN1"),
("Samoa","WSM"),
("Samoa Americana","ASM"),
("San Marino","SMR"),
("San Martín","SXM"),
("San Pedro y Miquelón","SPM"),
("San Vicente y las Granadinas","VCT"),
("Santa Elena","SHN"),
("Santa Lucía","LCA"),
("Santa Sede","VAT"),
("Santo Tomé y Príncipe","STP"),
("Sarawak","SWK"),
("Senegal","SEN"),
("Serbia, Rep. Fed. de (Serbia y Montenegro)","SER"),
("Seychelles","SYC"),
("Sierra Leona","SLE"),
("SIKKIM","SIK"),
("Singapur","SGP"),
("Somalia","SOM"),
("Sri Lanka","LKA"),
("Sudáfrica","ZAF"),
("Sudán","SUD"),
("Sudán del Sur","SSD"),
("Suecia","SWE"),
("Suiza","CHE"),
("Suriname","SUR"),
("Svalbard and Jan Mayen Is","SJM"),
("Swazilandia","SWZ"),
("Tailandia","THA"),
("Taiwán, China","TWN"),
("Tanzanía","TZA"),
("Tayikistán","TJK"),
("Territorio Antártico Británico","BAT"),
("Territorio Británico del Océano Índico","IOT"),
("Territorio Palestino Ocupado","PSE"),
("Tierras Australes y Antárticas Francesas","ATF"),
("Timor Oriental","TMP"),
("Togo","TGO"),
("Tokelau","TKL"),
("Tonga","TON"),
("Trinidad y Tobago","TTO"),
("Túnez","TUN"),
("Turkmenistán","TKM"),
("Turquía","TUR"),
("Tuvalu","TUV"),
("Ucrania","UKR"),
("Uganda","UGA"),
("Unión Soviética","SVU"),
("Uruguay","URY"),
("Uzbekistán","UZB"),
("Vanuatu","VUT"),
("Venezuela","VEN"),
("Vietnam","VNM"),
("Wake Island","WAK"),
("Rep. del Yemen","YEM"),
("Rep. Dem. Del Yemen","YDR"),
("Yugoslavia, Rep. Fed. de (Serbia y Montenegro)","YUG"),
("Zambia","ZMB"),
("Zimbabwe","ZWE");

INSERT INTO EMOTION_TYPE (name)
VALUES ('NEGATIVO'),
('POSITIVO'),
('NEUTRO');

INSERT INTO EMOTION (`name`, `emotiontype_Id`)
VALUES ('UNKNOWN', 3),
('HAPPY', 2),
('SAD', 1),
('ANGRY', 1),
('CONFUSED', 3),
('DISGUSTED', 1),
('SURPRISED', 3),
('CALM', 2),
('FEAR', 1);

INSERT INTO GENRE (name, createdAt, updatedAt)
VALUES ("Pop", NOW(), NOW()),
("Rock", NOW(), NOW()),
("Hip-Hop", NOW(), NOW()),
("Electronic Dance Music (EDM)", NOW(), NOW()),
("R&B/Soul", NOW(), NOW()),
("Jazz", NOW(), NOW()),
("Country", NOW(), NOW()),
("Latina", NOW(), NOW()),
("Clásica", NOW(), NOW()),
("Otro", NOW(), NOW());

INSERT INTO ARTIST (name, createdAt, updatedAt)
VALUES ("The Beatles", NOW(), NOW()),
("The Rolling Stones", NOW(), NOW()),
("Elton John", NOW(), NOW()),
("Mariah Carey", NOW(), NOW()),
("Madonna", NOW(), NOW()),
("Barbra Streisand", NOW(), NOW()),
("Michael Jackson", NOW(), NOW()),
("Taylor Swift", NOW(), NOW()),
("Stevie Wonder", NOW(), NOW()),
("Chicago", NOW(), NOW()),
("Whitney Houston", NOW(), NOW()),
("Paul McCartney", NOW(), NOW()),
("Elvis Presley", NOW(), NOW()),
("Janet Jackson", NOW(), NOW()),
("Rod Stewart", NOW(), NOW()),
("Drake", NOW(), NOW()),
("Prince", NOW(), NOW()),
("Rihanna", NOW(), NOW()),
("Billy Joel", NOW(), NOW()),
("Garth Brooks", NOW(), NOW()),
("Herb Alpert", NOW(), NOW()),
("Eminem", NOW(), NOW()),
("Usher", NOW(), NOW()),
("Bruce Springsteen", NOW(), NOW()),
("Neil Diamond", NOW(), NOW()),
("The Supremes", NOW(), NOW()),
("Eagles", NOW(), NOW()),
("Bee Gees", NOW(), NOW()),
("The Beach Boys", NOW(), NOW()),
("Fleetwood Mac", NOW(), NOW()),
("Santana", NOW(), NOW()),
("The Temptations", NOW(), NOW()),
("Celine Dion", NOW(), NOW()),
("Aretha Franklin", NOW(), NOW()),
("Daryl Hall John Oates", NOW(), NOW()),
("Adele", NOW(), NOW()),
("Beyonce", NOW(), NOW()),
("Eric Clapton", NOW(), NOW()),
("Lionel Richie", NOW(), NOW()),
("Led Zeppelin", NOW(), NOW()),
("Bruno Mars", NOW(), NOW()),
("John Denver", NOW(), NOW()),
("Maroon 5", NOW(), NOW()),
("Olivia Newton-John", NOW(), NOW()),
("Bon Jovi", NOW(), NOW()),
("Phil Collins", NOW(), NOW()),
("Diana Ross", NOW(), NOW()),
("Bob Dylan", NOW(), NOW()),
("John Mellencamp", NOW(), NOW()),
("JAY-Z", NOW(), NOW()),
("Donna Summer", NOW(), NOW()),
("Nickelback", NOW(), NOW()),
("Boyz II Men", NOW(), NOW()),
("Carpenters", NOW(), NOW()),
("Justin Bieber", NOW(), NOW()),
("Lady Gaga", NOW(), NOW()),
("Foreigner", NOW(), NOW()),
("Britney Spears", NOW(), NOW()),
("P!nk", NOW(), NOW()),
("Alicia Keys", NOW(), NOW()),
("Katy Perry", NOW(), NOW()),
("Miley Cyrus", NOW(), NOW()),
("The Jacksons", NOW(), NOW()),
("Earth, Wind & Fire", NOW(), NOW()),
("Marvin Gaye", NOW(), NOW()),
("U2", NOW(), NOW()),
("Linda Ronstadt", NOW(), NOW()),
("Van Halen", NOW(), NOW()),
("Bob Seger", NOW(), NOW()),
("Aerosmith", NOW(), NOW()),
("The Black Eyed Peas", NOW(), NOW()),
("Nelly", NOW(), NOW()),
("Carole King", NOW(), NOW()),
("Justin Timberlake", NOW(), NOW()),
("The Monkees", NOW(), NOW()),
("Kenny Rogers", NOW(), NOW()),
("Heart", NOW(), NOW()),
("Tim McGraw", NOW(), NOW()),
("Barry Manilow", NOW(), NOW()),
("R. Kelly", NOW(), NOW()),
("Journey", NOW(), NOW()),
("Simon & Garfunkel", NOW(), NOW()),
("Michael Bolton", NOW(), NOW()),
("Ed Sheeran", NOW(), NOW()),
("Kelly Clarkson", NOW(), NOW()),
("Pink Floyd", NOW(), NOW()),
("Queen", NOW(), NOW()),
("Mary J. Blige", NOW(), NOW()),
("Kanye West", NOW(), NOW()),
("Three Dog Night", NOW(), NOW()),
("Commodores", NOW(), NOW()),
("Paula Abdul", NOW(), NOW()),
("Bryan Adams", NOW(), NOW()),
("Chris Brown", NOW(), NOW()),
("Guns N' Roses", NOW(), NOW()),
("Def Leppard", NOW(), NOW()),
("Huey Lewis & The News", NOW(), NOW()),
("Linkin Park", NOW(), NOW()),
("James Taylor", NOW(), NOW()),
("Creedence Clearwater Revival", NOW(), NOW());

INSERT INTO SONG (name, createdAt, updatedAt)
VALUES ("Blinding Lights", NOW(), NOW()),
("The Twist", NOW(), NOW()),
("Smooth", NOW(), NOW()),
("Mack The Knife", NOW(), NOW()),
("Uptown Funk!", NOW(), NOW()),
("How Do I Live", NOW(), NOW()),
("Party Rock Anthem", NOW(), NOW()),
("I Gotta Feeling", NOW(), NOW()),
("Macarena (Bayside Boys Mix)", NOW(), NOW()),
("Shape Of You", NOW(), NOW()),
("Physical", NOW(), NOW()),
("You Light Up My Life", NOW(), NOW()),
("Hey Jude", NOW(), NOW()),
("Closer", NOW(), NOW()),
("We Belong Together", NOW(), NOW()),
("Un-Break My Heart", NOW(), NOW()),
("Yeah!", NOW(), NOW()),
("Bette Davis Eyes", NOW(), NOW()),
("Circles", NOW(), NOW()),
("Endless Love", NOW(), NOW()),
("Tonight's The Night (Gonna Be Alright)", NOW(), NOW()),
("Foolish Games/You Were Meant For Me", NOW(), NOW()),
("(Everything I Do) I Do It For You", NOW(), NOW()),
("I'Ll Make Love To You", NOW(), NOW()),
('The Theme From "A Summer Place"', NOW(), NOW()),
("Le Freak", NOW(), NOW()),
("How Deep Is Your Love", NOW(), NOW()),
("Eye Of The Tiger", NOW(), NOW()),
("We Found Love", NOW(), NOW()),
("Girls Like You", NOW(), NOW()),
("Low", NOW(), NOW()),
("Levitating", NOW(), NOW()),
("I Just Want To Be Your Everything", NOW(), NOW()),
("Too Close", NOW(), NOW()),
("Every Breath You Take", NOW(), NOW()),
("Somebody That I Used To Know", NOW(), NOW()),
("Despacito", NOW(), NOW()),
("Flashdance...What A Feeling", NOW(), NOW()),
("Rolling In The Deep", NOW(), NOW()),
("Tossin' And Turnin'", NOW(), NOW()),
("Old Town Road", NOW(), NOW()),
("The Battle Of New Orleans", NOW(), NOW()),
("One Sweet Day", NOW(), NOW()),
("Truly Madly Deeply", NOW(), NOW()),
("Silly Love Songs", NOW(), NOW()),
("Let's Get It On", NOW(), NOW()),
("Night Fever", NOW(), NOW()),
("Another One Bites The Dust", NOW(), NOW()),
("Mood", NOW(), NOW()),
("Say Say Say", NOW(), NOW()),
("How You Remind Me", NOW(), NOW()),
("Tie A Yellow Ribbon Round The Ole Oak Tree", NOW(), NOW()),
("It's All In The Game", NOW(), NOW()),
("I Want To Hold Your Hand", NOW(), NOW()),
("Shadow Dancing", NOW(), NOW()),
("Call Me Maybe", NOW(), NOW()),
("Blurred Lines", NOW(), NOW()),
("Candle In The Wind 1997/Something About The Way You Look Tonight", NOW(), NOW()),
("No One", NOW(), NOW()),
("I Will Always Love You", NOW(), NOW()),
("End Of The Road", NOW(), NOW()),
("Perfect", NOW(), NOW()),
("Boom Boom Pow", NOW(), NOW()),
("Call Me", NOW(), NOW()),
("Let Me Love You", NOW(), NOW()),
("Stayin' Alive", NOW(), NOW()),
("Lady", NOW(), NOW()),
("Tik Tok", NOW(), NOW()),
("I'm A Believer", NOW(), NOW()),
("Gold Digger", NOW(), NOW()),
("Apologize", NOW(), NOW()),
("The Sign", NOW(), NOW()),
("Centerfold", NOW(), NOW()),
("All About That Bass", NOW(), NOW()),
("Sunflower (Spider-Man: Into The Spider-Verse)", NOW(), NOW()),
("(Just Like) Starting Over", NOW(), NOW()),
("Royals", NOW(), NOW()),
("The Boy Is Mine", NOW(), NOW()),
("Because I Love You (The Postman Song)", NOW(), NOW()),
("I Love Rock 'N Roll", NOW(), NOW()),
("Aquarius/Let The Sunshine In (The Flesh Failures)", NOW(), NOW()),
("Whoomp! (There It Is)", NOW(), NOW()),
("God's Plan", NOW(), NOW()),
("Moves Like Jagger", NOW(), NOW()),
("Ebony And Ivory", NOW(), NOW()),
("Rush Rush", NOW(), NOW()),
("That's What Friends Are For", NOW(), NOW()),
("Happy", NOW(), NOW()),
("Upside Down", NOW(), NOW()),
("Sugar, Sugar", NOW(), NOW()),
("Just The Way You Are", NOW(), NOW()),
("Dilemma", NOW(), NOW()),
("I Heard It Through The Grapevine", NOW(), NOW()),
("You're Still The One", NOW(), NOW()),
("Billie Jean", NOW(), NOW()),
("Hot Stuff", NOW(), NOW()),
("Rockstar", NOW(), NOW()),
("Gangsta's Paradise", NOW(), NOW()),
("Abracadabra", NOW(), NOW()),
("You're So Vain", NOW(), NOW());

CREATE USER 'user'@'%' IDENTIFIED WITH caching_sha2_password BY 'user123';

GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD ON *.* TO 'user' WITH GRANT OPTION;